2022-05-25 11:13:01,446 DEBUG    root            Loaded Command Group: ['gcloud', 'container', 'clusters']
2022-05-25 11:13:01,447 DEBUG    root            Loaded Command Group: ['gcloud', 'container', 'clusters', 'get_credentials']
2022-05-25 11:13:01,458 DEBUG    root            Running [gcloud.container.clusters.get-credentials] with arguments: [NAME: "staging-cluster"]
2022-05-25 11:13:01,460 INFO     ___FILE_ONLY___ Fetching cluster endpoint and auth data.

2022-05-25 11:13:01,465 DEBUG    urllib3.connectionpool Starting new HTTPS connection (1): container.googleapis.com:443
2022-05-25 11:13:01,600 DEBUG    urllib3.connectionpool https://container.googleapis.com:443 "GET /v1/projects/crowdriff-stories-prod/locations/us-central1/clusters/staging-cluster?alt=json HTTP/1.1" 404 None
2022-05-25 11:13:01,936 DEBUG    urllib3.connectionpool https://container.googleapis.com:443 "GET /v1/projects/crowdriff-stories-prod/locations/-/clusters?alt=json HTTP/1.1" 200 None
2022-05-25 11:13:01,940 DEBUG    root            (gcloud.container.clusters.get-credentials) ResponseError: code=404, message=Not found: projects/crowdriff-stories-prod/locations/us-central1/clusters/staging-cluster.
No cluster named 'staging-cluster' in crowdriff-stories-prod.
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/lib/googlecloudsdk/api_lib/container/api_adapter.py", line 1292, in GetCluster
    return self.client.projects_locations_clusters.Get(
  File "/opt/homebrew/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/lib/googlecloudsdk/third_party/apis/container/v1/container_v1_client.py", line 520, in Get
    return self._RunMethod(
  File "/opt/homebrew/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/lib/third_party/apitools/base/py/base_api.py", line 737, in _RunMethod
    return self.ProcessHttpResponse(method_config, http_response, request)
  File "/opt/homebrew/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/lib/third_party/apitools/base/py/base_api.py", line 743, in ProcessHttpResponse
    self.__ProcessHttpResponse(method_config, http_response, request))
  File "/opt/homebrew/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/lib/third_party/apitools/base/py/base_api.py", line 609, in __ProcessHttpResponse
    raise exceptions.HttpError.FromResponse(
apitools.base.py.exceptions.HttpNotFoundError: HttpError accessing <https://container.googleapis.com/v1/projects/crowdriff-stories-prod/locations/us-central1/clusters/staging-cluster?alt=json>: response: <{'vary': 'Origin, X-Origin, Referer', 'content-type': 'application/json; charset=UTF-8', 'content-encoding': 'gzip', 'date': 'Wed, 25 May 2022 15:13:01 GMT', 'server': 'ESF', 'cache-control': 'private', 'x-xss-protection': '0', 'x-frame-options': 'SAMEORIGIN', 'x-content-type-options': 'nosniff', 'alt-svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"', 'transfer-encoding': 'chunked', 'status': 404}>, content <{
  "error": {
    "code": 404,
    "message": "Not found: projects/crowdriff-stories-prod/locations/us-central1/clusters/staging-cluster.",
    "status": "NOT_FOUND"
  }
}
>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/lib/googlecloudsdk/calliope/cli.py", line 987, in Execute
    resources = calliope_command.Run(cli=self, args=args)
  File "/opt/homebrew/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/lib/googlecloudsdk/calliope/backend.py", line 809, in Run
    resources = command_instance.Run(args)
  File "/opt/homebrew/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/lib/surface/container/clusters/get_credentials.py", line 113, in Run
    cluster, cluster_ref = _BaseRun(args, self.context)
  File "/opt/homebrew/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/lib/surface/container/clusters/get_credentials.py", line 41, in _BaseRun
    cluster = adapter.GetCluster(cluster_ref)
  File "/opt/homebrew/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/lib/googlecloudsdk/api_lib/container/api_adapter.py", line 1299, in GetCluster
    self.CheckClusterOtherZones(cluster_ref, api_error)
  File "/opt/homebrew/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/lib/googlecloudsdk/api_lib/container/api_adapter.py", line 1344, in CheckClusterOtherZones
    raise not_found_error
googlecloudsdk.api_lib.container.util.Error: ResponseError: code=404, message=Not found: projects/crowdriff-stories-prod/locations/us-central1/clusters/staging-cluster.
No cluster named 'staging-cluster' in crowdriff-stories-prod.
2022-05-25 11:13:01,944 ERROR    root            (gcloud.container.clusters.get-credentials) ResponseError: code=404, message=Not found: projects/crowdriff-stories-prod/locations/us-central1/clusters/staging-cluster.
No cluster named 'staging-cluster' in crowdriff-stories-prod.
2022-05-25 11:13:01,953 DEBUG    root            Metrics reporting process started...
